# Generated by Django 3.1.12 on 2021-07-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taski', '0002_menu_pynct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pynct',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='pynct',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Pynct',
        ),
    ]
