# Generated by Django 3.1.7 on 2021-07-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidjet',
            name='vidjetone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjetone', to='news.category', verbose_name='Виджет-1'),
        ),
        migrations.AddField(
            model_name='vidjet',
            name='vidjetthree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjetthree', to='news.category', verbose_name='Виджет-3'),
        ),
        migrations.AddField(
            model_name='vidjet',
            name='vidjettwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vidjettwo', to='news.category', verbose_name='Виджет-2'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slidertitle', to='news.post', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='saidebar',
            name='saidebar',
            field=models.ManyToManyField(related_name='saidebar', to='news.Category', verbose_name='Список'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='news.Category', verbose_name='Список'),
        ),
        migrations.AddField(
            model_name='favorit',
            name='favorit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit', to='news.category', verbose_name='Ибранная категория'),
        ),
    ]
