# Generated by Django 3.1.7 on 2021-07-22 17:06

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0003_footer_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikonki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('icon', faicon.fields.FAIconField(max_length=50, verbose_name='Иконка')),
                ('sylka', models.CharField(max_length=30, verbose_name='Сылка')),
                ('status', models.CharField(choices=[('True', 'Опубликовать'), ('False', 'Не публиковать')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
