# Generated by Django 2.2.2 on 2021-07-18 17:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUseris',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punct', models.CharField(max_length=255, verbose_name='Населеный пункт')),
            ],
            options={
                'verbose_name': 'Населеный пункт',
                'verbose_name_plural': 'Населеные пункты',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('punct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akaynt.Punkt', verbose_name='Населеный пункт')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.CreateModel(
            name='Klas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='P', max_length=30, verbose_name='Статус')),
                ('alf', models.CharField(choices=[('1', 'А'), ('2', 'Б'), ('3', 'В'), ('4', 'Г'), ('5', 'Д'), ('6', 'Е'), ('7', 'Ё'), ('8', 'Ж'), ('9', 'З'), ('10', 'И'), ('11', 'Й'), ('12', 'К'), ('13', 'Л'), ('14', 'М'), ('15', 'Н')], default='P', max_length=30, verbose_name='Статус')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akaynt.School', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школа',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('onli', models.BooleanField(default=False, verbose_name='Ученик онлайн')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Изображение')),
                ('dt', models.DateField(max_length=255, verbose_name='Дата рождения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
