# Generated by Django 3.1.7 on 2021-07-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akaynt', '0002_auto_20210718_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='punct',
        ),
        migrations.DeleteModel(
            name='Klas',
        ),
        migrations.DeleteModel(
            name='Punkt',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
